openapi: 3.0.0
title: Account/transaction app
version: 0.1
paths:
  '/accounttest/{customerId}':
    get:
      summary: output the user information showing Name, Surname, balance, and transactions of the accounts.
      operationId: accountTest
      parameters:
        - name: customerId
          in: path
          description: Customer identificator
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: user information and it's transaction
          # headers:
          #   x-next:
          #     description: A link to the next page of responses
          #     schema:
          #       type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/account/{customerId}':
    get:
      summary: output the user information showing Name, Surname, balance, and transactions of the accounts.
      operationId: accountInfo
      parameters:
        - name: customerId
          in: path
          description: Customer identificator
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: user information and it's transaction
          # headers:
          #   x-next:
          #     description: A link to the next page of responses
          #     schema:
          #       type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountSummary'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: creates an account for the customer
      operationId: accountCreate
      parameters:
        - name: customerId
          in: path
          description: Customer identificator
          required: true
          schema:
            type: string
            format: string
      responses:
        '201':
          description: the new account has been created for the customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    AccountSummary:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    User:
      type: object
      required:
        - name
        - surname
        - customerId
      properties:
        customerId:
          type: string
        name:
          type: string
        surname:
          type: string
    Transaction:
      type: object
      properties:
        date:
          type: integer
          format: int64
        amount:
          type: number
    Account:
      properties:
        id:
          type: integer
          format: int32
        customerId:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string  