openapi: 3.0.0
title: Account/transaction app
version: 0.1
paths:
  '/account/{customerId}':
    parameters:
      - name: customerId
        in: path
        required: true
        description: Customer identificator
        schema:
          type: string
    get:
      summary: output the user information showing Name, Surname, balance, and transactions of the accounts.
      operationId: accountInfo
      responses:
        '200':
          description: user information and it's transaction
          content:
            application/json:
              schema:
                type: object
                properties:
                  customer:
                    $ref: '#/components/schemas/Customer'
                  accounts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Account'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: creates an account for the customer
      operationId: accountCreate
      requestBody:
        description: Optional transaction amount to add
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                initialAmount:
                  type: number
      responses:
        '200':
          description: the new account has been created for the customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Customer:
      type: object
      required:
        - name
        - surname
        - customerId
      properties:
        customerId:
          type: string
          nullable: false
        name:
          type: string
          nullable: true
        surname:
          type: string
          nullable: true
    Transaction:
      type: object
      properties:
        uuid:
          type: string
          nullable: true
        date:
          type: integer
          format: int64
          nullable: true
        amount:
          type: number
          minimum: 0
          nullable: false
        credit:
          type: boolean
          nullable: false
        account:
          $ref: '#/components/schemas/Account'
    Account:
      type: object
      properties:
        uuid:
          type: string
        customerId:
          type: string
          nullable: false
        createdDate:
          type: integer
          format: int64
        balance:
          type: number
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string  